parameters:
  statbus:
    auth:
      discord: true
      tgstation: true
    badger: true
    manifest: false
    deaths:
      enabled: true
      heatmaps: true
    tickets:
      enabled: true
      public: true
    tgdb:
      enabled: true
      feedback: true
      allowList: true
      alts: true
      telemetry: true
      newplayers: true
    bans:
      public: true
    library: true
    polls: true
    round:
      logs: true
      map: true
    players:
      public: true
